In [1]:
import numpy as np

In [3]:
myList = [0, 1, 2, 3]

In [4]:
type(myList)

list

In [5]:
myListNP = np.array(myList)

In [6]:
myListNP

array([0, 1, 2, 3])

In [7]:
myMatrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(myMatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.linspace(0, 10, 51) # This command includes the end number

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [13]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
np.random.rand(10)

array([0.43808807, 0.59986051, 0.97274302, 0.16901363, 0.79885682,
       0.11583593, 0.18742019, 0.95842177, 0.15538408, 0.14068725])

In [18]:
np.random.rand(5, 2)

array([[0.99027425, 0.71660385],
       [0.72849781, 0.09624142],
       [0.69881997, 0.2110513 ],
       [0.76059326, 0.93683037],
       [0.39033873, 0.06266108]])

In [20]:
np.random.randn(10)

array([ 0.05735281, -1.97304863,  0.5511043 ,  0.32814598,  0.14387675,
       -0.98817268,  2.01162772, -0.31881575, -0.52920124,  1.62751506])

In [25]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [26]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [27]:
arr = np.arange(0, 25)

In [31]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
arr.dtype

dtype('int32')

In [34]:
arr.shape

(25,)

In [37]:
myarray = np.linspace(0, 10, 101)

In [39]:
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

---

In [2]:
arr = np.arange(0, 11)

In [3]:
arr[1:5]

array([1, 2, 3, 4])

In [4]:
arr[:3] = 100

In [5]:
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [7]:
partofArr = arr[2:6] # Use .copy() to prevent the following

In [8]:
partofArr

array([100,   3,   4,   5])

In [9]:
partofArr[:] = 9

In [10]:
partofArr

array([9, 9, 9, 9])

In [11]:
arr

array([100, 100,   9,   9,   9,   9,   6,   7,   8,   9,  10])

In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [13]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr_2d.shape

(3, 3)

In [15]:
arr_2d[0, 2]

3

In [4]:
arr_2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [5]:
arr_2d > 4

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [6]:
arr_2d[arr_2d > 4]

array([5, 6, 7, 8, 9])

In [7]:
arr_2d[arr_2d > 4].shape

(5,)

---